# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "💣💣💣" ]
  pull_request:
    branches: [ "💣💣💣" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install poetry
      - name: Install poetry
        run: pip install poetry

      # Install dev dependencies
      - name: Install poetry dependencies
        run: ./dev.sh install

      # Run coverage xml
#      - name: Run unittests with coverage and generate xml
#        run: ./dev.sh covxml
        
      # xml -> codecov
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v4
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
      # pylint
#      - name: Run pylint against the code
#        run: ./dev.sh pylint
